import React from 'react'

const Installation = () => {
  return (
    <div className='text-black px-4 py-8 '>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Id, Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ullam, quaerat? Sunt quis unde, laudantium odit, iusto rerum maxime numquam perferendis corrupti minima vitae? Dolor, quos aspernatur? Libero, inventore natus iure, delectus ipsam fuga placeat dolor cum repudiandae ad officia vero facilis aspernatur sequi nihil quae fugit eius explicabo tempora porro! Consectetur, ex molestias fugiat quo iste ratione debitis culpa. Aliquid, facilis, sit quos quod quae vel sunt error repellendus voluptate nobis dolorum molestiae? Sequi quasi hic earum corrupti natus assumenda nisi distinctio, ut quo nesciunt officiis eius est non incidunt temporibus itaque adipisci voluptatem et aliquid culpa iusto. In officiis voluptates labore debitis quidem repudiandae provident modi alias aspernatur inventore. Magnam ducimus quidem voluptatum, sunt veritatis rem nobis. Nobis unde qui obcaecati velit officia assumenda, quod reprehenderit perferendis veniam? Quod, odit eveniet. Eaque consequatur id quia, eligendi veniam voluptatibus quo laudantium amet voluptas dicta, est quam obcaecati veritatis similique reprehenderit commodi, temporibus labore ipsam beatae nostrum molestias minima recusandae sint facere. Iusto itaque doloremque sunt. Inventore nam modi hic nostrum asperiores natus, odit, porro adipisci assumenda fugit quo? Voluptate voluptatibus optio eos, ullam quos tenetur natus rerum, quis ipsa at eius! Nobis sint pariatur officiis quaerat aspernatur modi, ex optio incidunt natus officia earum quas. Et, alias blanditiis debitis reprehenderit enim laudantium repellat ad, delectus, quos non esse dignissimos. Dolorem hic commodi nemo unde? Dolorem voluptas soluta molestiae quas ex pariatur tenetur, rerum ea quod sequi, eveniet labore autem quis hic, ad repellendus? Voluptates vitae rerum nesciunt quod corporis a saepe ratione vel, tempore incidunt. Nulla quasi adipisci molestias explicabo nam. Minus eaque voluptatibus rem incidunt aut, nulla doloribus! Nulla saepe rerum hic maiores animi deserunt, at nesciunt quaerat officiis, illum eligendi ut dolores consequuntur accusantium minus reprehenderit obcaecati suscipit repellendus autem dolorum nisi libero incidunt excepturi neque? Vero, sequi. repellendus? Iusto quibusdam, temporibus maiores quod ipsa non, corporis libero, iure dicta facere officia itaque numquam in illum asperiores error sapiente.
    </div>
  )
}

export default Installation